/**
 * Finishes: surface effects, kept strictly separate from the colour systems.
 *
 * Texture effects are IMAGE TILES (base64 PNG data URIs from `src/data/textures.js`), not CSS
 * gradients. That is deliberate: `repeating-linear-gradient` can only draw regular patterns —
 * it produced graph paper where linen was asked for. The tiles are generated by
 * `tools/make-textures.py` and pass a numeric seam test (wrapped-edge delta <= 1.3x the
 * internal neighbour delta).
 *
 * Safety invariants carried over from the incident:
 *   * AT MOST ONE full-viewport overlay, enforced in `resolveFinishes`;
 *   * overlays sit at `z-index: 1` with `pointer-events: none`;
 *   * no `background-attachment: fixed`, no `!important` on painted backgrounds;
 *   * every texture stays faint — the overlay opacity is capped at 0.5.
 *
 * Bundling note: `@bundle:strip` blocks are test-only and removed by the bundler.
 */

/* @bundle:strip-start */
import { mixHex, toRgba } from './color.js';
import { TEXTURE_TILES } from '../data/textures.js';
/* @bundle:strip-end */

const FINISH_ORDER = [
  'glass',
  'gradient',
  'fiber',
  'cloud',
  'washi',
  'kraft',
  'linen',
  'rule',
  'halftone',
  'scanline',
  'emboss',
  'stroke',
  'shadow',
  'scroll',
];

/** Soften each other instead of refusing to combine. */
const DEGRADE_RULES = [
  { when: ['gradient', 'emboss'], note: '渐变 + 硬描边：硬描边保留描边，不铺底色' },
  { when: ['glass', 'fiber'], note: '毛玻璃 + 纤维：粒径减半，保住通透感' },
  { when: ['glass', 'cloud'], note: '毛玻璃 + 云絮：云絮减半，保住通透感' },
];

/**
 * The neutral light surface used when NO palette is selected ("官方原色").
 *
 * Why this exists: effects and colours are ADDITIVE, never substitutes. The build up to
 * 0.9.9 computed finishes only when a palette was active, so choosing 官方原色 silently threw
 * all fourteen effects away. Finishes now always resolve; without a palette they fall back to
 * this documented neutral.
 *
 * `brand` is deliberately a NEUTRAL GREY, not a real accent: the host's own brand colour is
 * not ours to guess, and inventing one would make "official colors + 焦点描边" quietly paint a
 * colour the user never chose.
 */
const NEUTRAL_LIGHT = {
  bg: '#FFFFFF',
  surface: '#FFFFFF',
  sunken: '#F2F3F5',
  text: '#1F2328',
  brand: '#8A8F98',
};

/** Shared geometry for the single permitted texture layer. */
const OVERLAY_BASE = 'position:fixed;inset:0;pointer-events:none;z-index:1;';

const SPIN_KEYFRAMES =
  '@keyframes dsh-theme-spin{to{transform:rotate(360deg)}}' +
  '@keyframes dsh-theme-pulse{0%,100%{opacity:.35}50%{opacity:1}}';

/** Texture overlays must stay faint enough to read text through (PRD FR-2). */
const TEXTURE_OPACITY = {
  fiber: 0.5,
  cloud: 0.45,
  washi: 0.45,
  kraft: 0.42,
  linen: 0.45,
  rule: 0.45,
  halftone: 0.32,
  scanline: 0.3,
};

/** One finish per generated tile, in the order the tiles are declared. */
const TEXTURE_FINISHES = Object.keys(TEXTURE_TILES).map((key) => ({
  id: key,
  name: TEXTURE_TILES[key].name,
  note: TEXTURE_TILES[key].note,
  tags: ['light', 'texture'],
  apply: (c, opts) => {
    const base = TEXTURE_OPACITY[key] === undefined ? 0.4 : TEXTURE_OPACITY[key];
    const alpha = opts && opts.softOverlays ? base / 2 : base;
    return {
      overlay:
        'opacity:' + alpha + ';' +
        'background-image:url(' + TEXTURE_TILES[key].dataUri + ');' +
        'background-repeat:repeat;background-size:128px 128px;',
    };
  },
}));

const CORE_FINISHES = [
  {
    id: 'glass',
    name: '毛玻璃',
    tags: ['light', 'neutral'],
    apply: (c) => ({
      tokens: {
        // "frosted", not "transparent": surfaces stay >=0.72 opaque (PRD FR-2)
        '--dsw-alias-bg-layer-1': toRgba(c.surface, 0.8),
        '--dsw-alias-bg-layer-2': toRgba(c.sunken, 0.72),
        '--dsw-alias-bg-overlay': toRgba(c.surface, 0.88),
        '--dsw-menu-surface-fill': toRgba(c.surface, 0.82),
        '--dsw-menu-backdrop-filter': 'saturate(140%) blur(10px)',
      },
    }),
  },
  {
    id: 'gradient',
    name: '渐变雾面',
    tags: ['light'],
    apply: (c) => ({
      // the base stays a COLOUR (translucent) so color-mix() consumers remain valid
      tokens: { '--dsw-alias-bg-base': toRgba(c.bg, 0.86) },
      css:
        'html{background-image:linear-gradient(158deg,' + c.bg + ' 0%,' + c.tintA + ' 52%,' + c.tintB + ' 100%);}' +
        'body{background-color:transparent;}',
    }),
  },
];

const TAIL_FINISHES = [
  {
    id: 'emboss',
    name: '硬描边',
    tags: ['light', 'neutral'],
    apply: (c) => ({
      // an inset shadow on `body` is invisible (the shell frame paints over it) — only the
      // border tokens do visible work here
      tokens: {
        '--dsw-alias-border-l1': mixHex(c.surface, c.ink, 0.38),
        '--dsw-alias-border-l2': mixHex(c.surface, c.ink, 0.5),
        '--dsw-elevation-stroke-color': mixHex(c.surface, c.ink, 0.46),
      },
    }),
  },
  {
    id: 'stroke',
    name: '焦点描边',
    tags: ['light', 'neutral'],
    apply: (c) => ({
      tokens: {
        '--dsw-alias-border-l1': mixHex(c.surface, c.accent, 0.34),
        '--dsw-alias-border-l3': mixHex(c.surface, c.accent, 0.48),
        '--dsw-focus-ring-width': '3px',
      },
    }),
  },
  {
    id: 'shadow',
    name: '浮层投影',
    tags: ['light', 'neutral'],
    apply: (c) => ({
      // consumed as `box-shadow: var(--dsw-elevation-panel)` — which the host only uses on
      // floating surfaces (menus, floating buttons, previews), hence the name
      tokens: {
        '--dsw-elevation-panel': '0 14px 40px ' + toRgba(c.ink, 0.14),
        '--dsw-elevation-prominent': '0 22px 60px ' + toRgba(c.ink, 0.2),
        '--dsw-elevation-soft': '0 10px 28px ' + toRgba(c.ink, 0.12),
      },
    }),
  },
  {
    id: 'scroll',
    name: '描金滚动条',
    tags: ['light', 'neutral'],
    apply: (c) => ({
      tokens: {
        // the host rebinds --dsh-scrollbar-thumb per container to these alias tokens, so the
        // alias pair is the lever that reaches the thumb; the width token makes it visible
        '--dsw-alias-scrollbar-bg-l2': mixHex(c.accent, c.surface, 0.3),
        '--dsw-alias-scrollbar-hover-l2': c.accent,
        '--dsh-scrollbar-width': '8px',
      },
    }),
  },
];

const FINISHES = CORE_FINISHES.concat(TEXTURE_FINISHES, TAIL_FINISHES);

const FINISH_BY_ID = FINISHES.reduce((acc, f) => {
  acc[f.id] = f;
  return acc;
}, {});

/**
 * Compose the enabled finishes over one palette.
 *
 * `palette` may be null (官方原色): effects are additive with colour, so they must still
 * resolve — they simply lose the palette tint and use `NEUTRAL_LIGHT`.
 *
 * @returns `{ tokens, css, overlayCount, notes, order }`
 */
function resolveFinishes(finishIds, palette) {
  const spec = (palette && palette.light) || NEUTRAL_LIGHT;
  const colors = {
    bg: spec.bg,
    surface: spec.surface,
    sunken: spec.sunken,
    ink: spec.text,
    accent: spec.brand,
    tintA: mixHex(spec.bg, spec.brand, 0.12),
    tintB: mixHex(spec.bg, spec.brand, 0.05),
  };

  const requested = (finishIds || []).filter((id) => Boolean(FINISH_BY_ID[id]));
  const ordered = FINISH_ORDER.filter((id) => requested.indexOf(id) >= 0);
  const notes = [];
  for (const rule of DEGRADE_RULES) {
    if (rule.when.every((id) => ordered.indexOf(id) >= 0)) notes.push(rule.note);
  }

  const opts = {
    softOverlays: ordered.indexOf('glass') >= 0,
    hasGradient: ordered.indexOf('gradient') >= 0,
  };

  const tokens = {};
  let css = '';
  const overlays = [];
  for (const id of ordered) {
    const out = FINISH_BY_ID[id].apply(colors, opts) || {};
    if (out.tokens) Object.assign(tokens, out.tokens);
    if (out.css) css += out.css;
    if (out.overlay) overlays.push({ id, body: out.overlay });
  }

  // HARD CAP: one full-viewport layer, no matter what state asked for.
  const chosen = overlays.slice(0, 1);
  if (overlays.length > 1) {
    notes.push(
      '只允许一个全屏纹理层：已采用「' + FINISH_BY_ID[chosen[0].id].name + '」',
    );
  }
  if (chosen.length) {
    css += 'body::after{content:"";' + OVERLAY_BASE + chosen[0].body + '}';
  }

  return { tokens, css, overlayCount: chosen.length, notes, order: ordered };
}

/** The documented kill switch: an empty composition that paints nothing at all. */
function emptyComposition() {
  return { tokens: {}, css: '', overlayCount: 0, notes: [], order: [] };
}

/* @bundle:strip-start */
export {
  FINISHES,
  FINISH_BY_ID,
  FINISH_ORDER,
  DEGRADE_RULES,
  TEXTURE_OPACITY,
  OVERLAY_BASE,
  NEUTRAL_LIGHT,
  resolveFinishes,
  emptyComposition,
  SPIN_KEYFRAMES,
};
/* @bundle:strip-end */
